name: Android Build (Vite + Capacitor)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend-vite
          npm install

      - name: Build frontend (Vite)
        run: |
          cd frontend-vite
          npm run build

      - name: Setup Java (for Gradle)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Initialize Capacitor (if needed)
        run: |
          cd frontend-vite
          npx cap init android com.example.app "AutoBithumbApp" || true

      - name: Add Android platform (idempotent)
        run: |
          cd frontend-vite
          npx cap add android || true

      - name: Copy built web to Android project
        run: |
          cd frontend-vite
          npx cap copy android

      - name: Build Android APK
        run: |
          cd frontend-vite/android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: frontend-vite/android/app/build/outputs/apk/debug/app-debug.apk
